# Generated by Django 5.0.4 on 2025-06-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionactividad',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='asignacionactividad',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='costodirecto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='costototalproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='AsignacionActividad',
        ),
        migrations.DeleteModel(
            name='CostoDirecto',
        ),
        migrations.DeleteModel(
            name='CostoTotalProducto',
        ),
    ]
