# Generated by Django 5.0.4 on 2025-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexmateriaprima',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
