# Generated by Django 5.0.4 on 2025-06-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_kardexmateriaprima_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexproductoterminado',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
