# Generated by Django 5.0.4 on 2025-05-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_empleado_planilla_detalleplanilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='fecha',
        ),
        migrations.AddField(
            model_name='planilla',
            name='anio',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planilla',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=5),
            preserve_default=False,
        ),
    ]
