# Generated by Django 5.0.4 on 2025-05-25 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_balancegeneral_detallebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('cuenta_costo_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_costo', to='contabilidad.cuentacontable')),
                ('cuenta_ingresos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_ingresos', to='contabilidad.cuentacontable')),
                ('cuenta_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_inventario', to='contabilidad.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.13, max_digits=10)),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.asientocontable')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.producto')),
            ],
        ),
    ]
