# Generated by Django 4.2.11 on 2025-05-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_estadoresultados_detalleresultado'),
        ('contabilidad', '0006_producto_movimientoinventario'),
    ]

    operations = [
    ]
