# Generated by Django 5.0.4 on 2025-05-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_merge_20250525_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
    ]
