# Generated by Django 5.0.4 on 2025-05-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_remove_producto_precio_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleplanilla',
            old_name='afp',
            new_name='afp_patronal',
        ),
        migrations.RenameField(
            model_name='detalleplanilla',
            old_name='renta',
            new_name='isss_patronal',
        ),
    ]
