# Generated by Django 5.0.4 on 2025-05-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_rename_afp_detalleplanilla_afp_patronal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanilla',
            name='total_costo_empleador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
