# Generated by Django 5.0.4 on 2025-05-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_detalleplanilla_total_costo_empleador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleplanilla',
            old_name='afp_patronal',
            new_name='afp',
        ),
        migrations.RenameField(
            model_name='detalleplanilla',
            old_name='isss_patronal',
            new_name='isss',
        ),
        migrations.AlterField(
            model_name='detalleplanilla',
            name='total_costo_empleador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
