# Generated by Django 4.2.11 on 2025-05-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_actividad_centrocosto_asignacionabc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_consumo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CostoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mano_obra_directa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('materia_prima_directa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limpieza_moldes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_costos_indirectos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_costos_directos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='actividad',
            name='unidad_medida',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.DeleteModel(
            name='AsignacionABC',
        ),
        migrations.DeleteModel(
            name='CentroCosto',
        ),
        migrations.AddField(
            model_name='consumoactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.actividad'),
        ),
        migrations.AddField(
            model_name='consumoactividad',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.producto'),
        ),
    ]
