# Generated by Django 4.2.11 on 2025-05-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_consumoactividad_costodirecto_resumencostos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostoTotalProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_indirecto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_producida', models.PositiveIntegerField(default=0)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='resumencostos',
            name='producto',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='unidad_medida',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ConsumoActividad',
        ),
        migrations.DeleteModel(
            name='ResumenCostos',
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.actividad'),
        ),
        migrations.AddField(
            model_name='asignacionactividad',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.producto'),
        ),
    ]
