# Generated by Django 4.2.11 on 2025-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_asignacionactividad_costototalproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='mes_anio',
            field=models.CharField(blank=True, help_text='Ejemplo: Marzo 2025', max_length=20, null=True),
        ),
    ]
