# Generated by Django 4.2.11 on 2025-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_actividad_mes_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='mes_anio',
        ),
        migrations.AddField(
            model_name='actividad',
            name='anio',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='mes',
            field=models.CharField(blank=True, choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, null=True),
        ),
    ]
